# This is a basic workflow to help you get started with Actions

name: pytest

# Controls when the workflow will run. Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the "main" branch


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_on_linux"
  pytest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
  
      # Runs a single command using the runners shell
      - name: checkout repository
        uses: actions/checkout@v3   
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
      - name: check the env
        run: env
      - name: check the git hub repo
        run: echo $GITHUB_REPOSITORY
     
